# Site
name: "Francisco Dorado"
title: "Francisco Dorado - Software Engineer"
description: "Java & Spring Backend (+10 years experience). Cloud with AWS. Architecture oriented."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-164934904-1'
disqus: 'https-frandorado-github-io'
mailchimp-list: 'https://github.us8.list-manage.com/subscribe/post?u=5072924fb3fe24917b8a6edfc&amp;id=7284b8fc21'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  frandorado:
    name: Francisco Dorado
    display_name: Francisco Dorado
    avatar: 'assets/images/avatar.png'
    #gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: doradofran@gmail.com
    web: https://www.linkedin.com/in/franciscodorado/
    twitter: https://twitter.com/frandorado
    description: "Software Architect at sngular.com in Seville. Specialised in backend technologies based in the Java ecosystem. Currently working on Microservices using Spring Framework and AWS Cloud technologies"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
#adsense-data-ad-client: "ca-pub-3412143450191416"
#adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

collections:
  projects:
    output: true
    permalink: /project/:path/
      
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title:output_ext

statisticsUrl: "https://doradofran.pythonanywhere.com"

